parent_cfg: configs/enerf/dtu_pretrain.yaml

train_dataset_module: lib.datasets.nerf.enerf
test_dataset_module: lib.datasets.nerf.enerf

enerf:
    cas_config:
        render_if: [False, True]

train_dataset:
    data_root: 'nerf_synthetic' #
    split: 'train'
    batch_size: 1
    input_ratio: 1.

test_dataset:
    data_root: 'nerf_synthetic' #
    split: 'test'
    batch_size: 1
    input_ratio: 1.
